package Display;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridBagLayout;

import javax.swing.*;

public class GameWindow extends JFrame {
    private JButton addStructButton;
    private JButton addRoadButton;
    private JButton upgradeButton;
    private JButton drawCard;
    private JList<String> jList1;
    private JPanel jMenu;
    private JPanel jBoard;
    // End of variables declaration

    public GameWindow() {
        // Creation de la fenetre
        setTitle("COLON DE CATANE");
        setSize(8000, 6000);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        jMenu = new JPanel();
        jBoard = new JPanel();
        jMenu.setBackground(new Color(255,215,0));
        jBoard.setBackground(new Color(0,215,255));
        this.getContentPane().setLayout(new GridBagLayout());
        this.getContentPane().add(jBoard);
        this.getContentPane().add(jMenu);

        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

}